//@version=3

study(title="Price Change History", shorttitle="History")

src = input(close, title="Source")
since = input(1, title="Since", minval=1)
limit = input(5, title="Highlight If Above", type=float, minval=0)
diff = input(true, title="Percentage") ? change(src, since) / offset(src, since) * 100 : change(src, since)

paint(x) => abs(x) > limit ? orange : x > 0 ? green : red

plot(diff, style=columns, color=paint(diff))
