//@version=4

// https://github.com/chingc/TradingView

study(title="Moving Average Ribbon", shorttitle="Ribbon", overlay=true)

src = input(close, title="Source")
exp = input(true, title="Exponential")
show_100 = input(true, title="MA 100")
show_200 = input(true, title="MA 200")

ma(length) => exp ? ema(src, length) : sma(src, length)

plot(ma(20), title="MA 20", color=#FFFF0080)
plot(ma(25), title="MA 25", color=#FFDF0080)
plot(ma(30), title="MA 30", color=#FFBF0080)
plot(ma(35), title="MA 35", color=#FF9F0080)
plot(ma(40), title="MA 40", color=#FF7F0080)
plot(ma(45), title="MA 45", color=#FF5F0080)
plot(ma(50), title="MA 50", color=#FF3F0080)

ma_100 = ma(100)
ma_200 = ma(200)
p_100 = plot(show_100 ? ma_100 : na, title="MA 100", color=#FF0000)
p_200 = plot(show_200 ? ma_200 : na, title="MA 200", color=#800000)
fill(p_100, p_200, color=(ma_100 > ma_200 ? color.green : color.red), transp=80, title="MA Fill")
